proxy:
  basics:
    host: "127.0.0.1"
    port: 1234
  servers:
    - name: "PRIMARY"
      id: "P1"
      host: "192.168.250.230"
      port: 3306
      required: true
      test_db: "test"
      default: true
    - name: "REPLICA"
      id: "R1"
      host: "192.168.250.230"
      port: 3306
  rules:
    - name: "REDIRECT SELECT FOR UPDATE QUERIES TO PRIMARY"
      regex_rule: "^SELECT FOR UPDATE.*"
      target_id: "P1"
    - name: "REDIRECT SELECT QUERIES TO REPLICA"
      regex_rule: "^SELECT.*"
      target_id: "R1"
    - name: "SELECT * FROM versions WHERE major=?"
      hash_rule: "3c343df0eb5b1832b1c8443e63340718dae9c8dbaaa43193e3db435d40dffe94"
      target_id: "R1"
  access:
    user: "user"
    password: ""
  db_users:
    - target: "P1"
      user: "root"
      password: "passwd"
    - target: "R1"
      user: "root"
      password: "passwd"
