proxy:
  port: 6666
  servers:
    - name: "PRIMARY"
      id: "P1"
      host: "127.0.0.1"
      port: 3306
    - name: "REPLICA"
      id: "R1"
      host: "192.168.250.230"
      port: 3306
  rules:
    - name: "REDIRECT SELECT QUERIES TO REPLICA"
      regex_rule: "SELECT.*"
      target_id: "R1"
    - name: "REDIRECT SELECT FOR UPDATE QUERIES TO PRIMARY"
      regex_rule: "UPDATE FOR SELECT.*"
      target_id: "P1"
  access:
    user: "user"
    password: "password"
  db_users:
    - target: "P1"
      user: "P1_user"
      password: "P1_password"
    - target: "R1"
      user: "R1_user"
      password: "R1_password"