#!/bin/bash

mysql -u root -p$MYSQL_ROOT_PASSWORD -e"CREATE USER '$GOPROXY_REPLICATION_USER'@'%' IDENTIFIED WITH mysql_native_password BY '$GOPROXY_REPLICATION_PASSWORD';"
mysql -u root -p$MYSQL_ROOT_PASSWORD -e"GRANT REPLICATION SLAVE ON *.* TO '$GOPROXY_REPLICATION_USER'@'%';"
mysql -u root -p$MYSQL_ROOT_PASSWORD -e"FLUSH PRIVILEGES;"
mysql -u root -p$MYSQL_ROOT_PASSWORD -e"SHOW BINARY LOG STATUS\G;"
