#!/bin/bash

mysql -u root -p$MYSQL_ROOT_PASSWORD -e"STOP REPLICA;CHANGE REPLICATION SOURCE TO
  SOURCE_HOST='$GOPROXY_MASTER_HOSTNAME',
  SOURCE_USER='$GOPROXY_REPLICATION_USER',
  SOURCE_PASSWORD='$GOPROXY_REPLICATION_PASSWORD',
  SOURCE_LOG_FILE='$1',
  SOURCE_LOG_POS=$2;"
mysql -u root -p$MYSQL_ROOT_PASSWORD -e"START SLAVE;"
sleep 5s
mysql -u root -p$MYSQL_ROOT_PASSWORD -e"SHOW SLAVE STATUS\G;"
